version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    aws:
      patterns:
      - "aws-*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
