[package]
name = "ctrl-cidr"
version = "0.3.0"
authors = ["LOU Xun <xun.lou@controlant.com>"]
description = "CIDR rules controller for AWS networking"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", default-features = false, features = ["std", "derive"] }
log = "0.4"
env_logger = "0.9"
ipnet = "2"

# AWS
aws-types = "0.47"
aws-config = "0.48"
aws-sdk-ec2 = "0.17"
aws-sdk-eks = "0.17"

# Runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
