name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, prefix with v, e.g. v1.0.0'
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - run: |
        sed '3s/^version.*$/version = "${{ inputs.version }}"/' -i Cargo.toml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Cargo.toml
        git commit -m "Release ${{ inputs.version }}"
        git tag ${{ inputs.version }}
        git push ${{ inputs.version }}
